FROM node:20-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем db.json
COPY db.json ./

# Запускаем json-server через npm run server
EXPOSE 3001
CMD ["npm", "run", "server"]
